<?php

/**
 * This is the model base class for the table "message".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Message".
 *
 * Columns in table "message" available as properties of the model,
 * followed by relations of table "message" available as properties of the model.
 *
 * @property integer $message_id
 * @property integer $chatting_id
 * @property integer $user
 * @property string $content
 * @property integer $date
 *
 * @property Chatting $chatting
 */
abstract class BaseMessage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'message';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Message|Messages', $n);
	}

	public static function representingColumn() {
		return 'content';
	}

	public function rules() {
		return array(
			array('message_id, chatting_id, user, content, date', 'required'),
			array('message_id, chatting_id, user, date', 'numerical', 'integerOnly'=>true),
			array('message_id, chatting_id, user, content, date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'chatting' => array(self::BELONGS_TO, 'Chatting', 'chatting_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'message_id' => Yii::t('app', 'Message'),
			'chatting_id' => null,
			'user' => Yii::t('app', 'User'),
			'content' => Yii::t('app', 'Content'),
			'date' => Yii::t('app', 'Date'),
			'chatting' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('message_id', $this->message_id);
		$criteria->compare('chatting_id', $this->chatting_id);
		$criteria->compare('user', $this->user);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('date', $this->date);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}