<?php

/**
 * This is the model base class for the table "user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "user" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $userid
 * @property string $user
 * @property string $password
 * @property string $first_name
 * @property string $last_name
 * @property integer $date
 * @property string $address
 * @property string $avatar
 * @property string $cover
 * @property string $phone
 * @property string $career
 * @property integer $location_id
 * @property integer $chatting_id
 * @property string $email
 * @property string $gender
 * @property string $description
 *
 */
abstract class BaseUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'user';
	}

	public function rules() {
		return array(
			array('date, location_id, chatting_id', 'numerical', 'integerOnly'=>true),
			array('user, password, first_name, last_name, address, avatar, cover, phone, career, email, description', 'length', 'max'=>255),
			array('gender', 'length', 'max'=>11),
			array('user, password, first_name, last_name, date, address, avatar, cover, phone, career, location_id, chatting_id, email, gender, description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('userid, user, password, first_name, last_name, date, address, avatar, cover, phone, career, location_id, chatting_id, email, gender, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'userid' => Yii::t('app', 'Userid'),
			'user' => Yii::t('app', 'User'),
			'password' => Yii::t('app', 'Password'),
			'first_name' => Yii::t('app', 'First Name'),
			'last_name' => Yii::t('app', 'Last Name'),
			'date' => Yii::t('app', 'Date'),
			'address' => Yii::t('app', 'Address'),
			'avatar' => Yii::t('app', 'Avatar'),
			'cover' => Yii::t('app', 'Cover'),
			'phone' => Yii::t('app', 'Phone'),
			'career' => Yii::t('app', 'Career'),
			'location_id' => Yii::t('app', 'Location'),
			'chatting_id' => Yii::t('app', 'Chatting'),
			'email' => Yii::t('app', 'Email'),
			'gender' => Yii::t('app', 'Gender'),
			'description' => Yii::t('app', 'Description'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('userid', $this->userid);
		$criteria->compare('user', $this->user, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('first_name', $this->first_name, true);
		$criteria->compare('last_name', $this->last_name, true);
		$criteria->compare('date', $this->date);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('avatar', $this->avatar, true);
		$criteria->compare('cover', $this->cover, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('career', $this->career, true);
		$criteria->compare('location_id', $this->location_id);
		$criteria->compare('chatting_id', $this->chatting_id);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('gender', $this->gender, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}