<?php

/**
 * This is the model base class for the table "user_subject".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserSubject".
 *
 * Columns in table "user_subject" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $user_id
 * @property integer $subject_id
 * @property integer $year
 * @property integer $like
 *
 */
abstract class BaseUserSubject extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_subject';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserSubject|UserSubjects', $n);
	}

	public static function representingColumn() {
		return array(
			'user_id',
			'subject_id',
		);
	}

	public function rules() {
		return array(
			array('user_id, subject_id, year, like', 'required'),
			array('user_id, subject_id, year, like', 'numerical', 'integerOnly'=>true),
			array('user_id, subject_id, year, like', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => null,
			'subject_id' => null,
			'year' => Yii::t('app', 'Year'),
			'like' => Yii::t('app', 'Like'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('subject_id', $this->subject_id);
		$criteria->compare('year', $this->year);
		$criteria->compare('like', $this->like);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}