<?php

/**
 * This is the model base class for the table "subject_group".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SubjectGroup".
 *
 * Columns in table "subject_group" available as properties of the model,
 * followed by relations of table "subject_group" available as properties of the model.
 *
 * @property integer $subject_group_id
 * @property string $name
 * @property string $description
 *
 * @property Subject[] $subjects
 */
abstract class BaseSubjectGroup extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'subject_group';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SubjectGroup|SubjectGroups', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('subject_group_id, name, description', 'required'),
			array('subject_group_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('subject_group_id, name, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'subjects' => array(self::HAS_MANY, 'Subject', 'subject_group_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'subject_group_id' => Yii::t('app', 'Subject Group'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'subjects' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('subject_group_id', $this->subject_group_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}